version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "3500:3500"
    environment:
      DB_USER: todo_user
      DB_HOST: db       # This matches the service name
      DB_NAME: todo_db
      DB_PASS: todo_pass
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3500
    depends_on:
      - backend
